# Generated by Django 5.2.17 on 2026-08-20 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="petconversation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="petmemory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="petmemory",
            name="memory_type",
            field=models.CharField(
                choices=[
                    ("identity", "Identity"),
                    ("preference", "Preference"),
                    ("project", "Project"),
                    ("decision", "Decision"),
                    ("goal", "Goal"),
                    ("skill", "Skill"),
                    ("experience", "Experience"),
                ],
                default="experience",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="petprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="petprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
