# Generated by Django 5.2.17 on 2026-08-20 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0002_alter_petaction_id_alter_petconversation_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("unlocked", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name="petconversation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="petconversation",
            old_name="content",
            new_name="pet_response",
        ),
        migrations.RenameField(
            model_name="petmemory",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RemoveField(
            model_name="petconversation",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="petconversation",
            name="role",
        ),
        migrations.RemoveField(
            model_name="petmemory",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="petmemory",
            name="importance",
        ),
        migrations.RemoveField(
            model_name="petmemory",
            name="memory_type",
        ),
        migrations.RemoveField(
            model_name="petmemory",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="petmemory",
            name="related_id",
        ),
        migrations.RemoveField(
            model_name="petmemory",
            name="related_type",
        ),
        migrations.RemoveField(
            model_name="petprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="petprofile",
            name="mood",
        ),
        migrations.RemoveField(
            model_name="petprofile",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="petprofile",
            name="personality",
        ),
        migrations.RemoveField(
            model_name="petprofile",
            name="species",
        ),
        migrations.AddField(
            model_name="petconversation",
            name="emotion",
            field=models.CharField(default="happy", max_length=50),
        ),
        migrations.AddField(
            model_name="petconversation",
            name="pet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="pet.petprofile",
            ),
        ),
        migrations.AddField(
            model_name="petconversation",
            name="user_message",
            field=models.TextField(default="unknown"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="petprofile",
            name="curiosity",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="energy",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="focus",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="happiness",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="petprofile",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="petprofile",
            name="name",
            field=models.CharField(default="Voxie", max_length=50),
        ),
        migrations.AlterField(
            model_name="petprofile",
            name="xp",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="PetAction",
        ),
    ]
