# Generated by Django 5.2.17 on 2026-08-20 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0003_petability_alter_petconversation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="petprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="petprofile",
            name="current_state",
            field=models.CharField(default="idle", max_length=50),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pet_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
