# Initial PixelVault schema.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import django.utils.timezone
import workspace.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(default="Local Builder", max_length=60)),
                ("role", models.CharField(default="Maker / Builder", max_length=80)),
                ("workspace_name", models.CharField(default="PixelVault", max_length=60)),
                ("social_handle", models.CharField(blank=True, max_length=60)),
                ("bio", models.CharField(blank=True, max_length=280)),
                ("avatar", models.CharField(default="mascot-cat.webp", max_length=64)),
                ("theme", models.CharField(choices=[("pixel-night", "Pixel Night"), ("neon-cyan", "Neon Circuit"), ("synthwave", "Synth Sunset"), ("terminal", "Terminal Green"), ("amber-crt", "Amber CRT"), ("paper-light", "Pixel Paper"), ("candy-light", "Candy Desktop")], default="pixel-night", max_length=32)),
                ("accent", models.CharField(choices=[("pink", "Pink"), ("cyan", "Cyan"), ("lime", "Lime"), ("yellow", "Yellow"), ("violet", "Violet"), ("orange", "Orange")], default="pink", max_length=16)),
                ("density", models.CharField(choices=[("comfortable", "Comfortable"), ("compact", "Compact")], default="comfortable", max_length=16)),
                ("text_size", models.CharField(choices=[("normal", "Normal"), ("large", "Large"), ("xlarge", "Extra Large")], default="large", max_length=16)),
                ("reduce_motion", models.BooleanField(default=False)),
                ("show_grid", models.BooleanField(default=True)),
                ("show_mascots", models.BooleanField(default=True)),
                ("confirm_deletes", models.BooleanField(default=True)),
                ("high_contrast", models.BooleanField(default=False)),
                ("large_targets", models.BooleanField(default=False)),
                ("landing_page", models.CharField(choices=[("home", "Home"), ("ideas", "Ideas"), ("projects", "Projects"), ("tasks", "Tasks"), ("planner", "Planner"), ("skills", "Skills"), ("reports", "Reports"), ("annotations", "Annotations"), ("settings", "Settings")], default="home", max_length=20)),
                ("planner_default_view", models.CharField(choices=[("daily", "Daily"), ("weekly", "Weekly"), ("calendar", "Calendar")], default="weekly", max_length=16)),
                ("planner_view", models.CharField(choices=[("daily", "Daily"), ("weekly", "Weekly"), ("calendar", "Calendar")], default="weekly", max_length=16)),
                ("planner_anchor", models.DateField(default=django.utils.timezone.localdate)),
                ("week_start", models.CharField(choices=[("monday", "Monday"), ("sunday", "Sunday")], default="monday", max_length=10)),
                ("workday_start", models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(23)])),
                ("workday_end", models.PositiveSmallIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ("default_task_duration", models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ("default_highlight", models.CharField(choices=[("yellow", "Yellow"), ("pink", "Pink"), ("cyan", "Cyan"), ("lime", "Lime")], default="yellow", max_length=16)),
                ("show_highlights", models.BooleanField(default=True)),
                ("signature", models.CharField(blank=True, max_length=80)),
                ("skill_selected", models.CharField(blank=True, max_length=64)),
                ("workspace_root", models.CharField(blank=True, max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="pixelvault_settings", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.CharField(default=workspace.models.project_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("active", "Active"), ("paused", "Paused"), ("done", "Done")], default="active", max_length=20)),
                ("progress", models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ("local_path", models.CharField(blank=True, max_length=1024)),
                ("launch_url", models.URLField(blank=True, max_length=1000)),
                ("repository_url", models.URLField(blank=True, max_length=1000)),
                ("tech_stack", models.JSONField(blank=True, default=list)),
                ("is_web", models.BooleanField(default=False)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("goal", models.TextField(blank=True)),
                ("next_milestone", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("pinned", models.BooleanField(default=False)),
                ("created_on", models.DateField(default=django.utils.timezone.localdate)),
                ("updated_on", models.DateField(default=django.utils.timezone.localdate)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pixelvault_projects", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-pinned", "-updated_on", "title"]},
        ),
        migrations.CreateModel(
            name="Idea",
            fields=[
                ("id", models.CharField(default=workspace.models.idea_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("content_type", models.CharField(choices=[("note", "Note"), ("prompt", "Prompt"), ("webpage", "Webpage"), ("reference", "Reference")], default="note", max_length=20)),
                ("content", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("inbox", "Inbox"), ("exploring", "Exploring"), ("ready", "Ready"), ("building", "Building")], default="inbox", max_length=20)),
                ("priority", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], default="medium", max_length=12)),
                ("goal", models.TextField(blank=True)),
                ("audience", models.CharField(blank=True, max_length=180)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("next_action", models.CharField(blank=True, max_length=500)),
                ("pinned", models.BooleanField(default=False)),
                ("created_on", models.DateField(default=django.utils.timezone.localdate)),
                ("updated_on", models.DateField(default=django.utils.timezone.localdate)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pixelvault_ideas", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ideas", to="workspace.project")),
            ],
            options={"ordering": ["-pinned", "-updated_on", "title"]},
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.CharField(default=workspace.models.task_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("todo", "Todo"), ("doing", "Doing"), ("done", "Done")], default="todo", max_length=12)),
                ("priority", models.CharField(choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")], default="medium", max_length=12)),
                ("task_type", models.CharField(blank=True, default="development", max_length=40)),
                ("energy", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], default="medium", max_length=12)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=45, validators=[django.core.validators.MaxValueValidator(1440)])),
                ("recurrence", models.CharField(choices=[("none", "None"), ("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")], default="none", max_length=12)),
                ("subtasks", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("pinned", models.BooleanField(default=False)),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("created_on", models.DateField(default=django.utils.timezone.localdate)),
                ("updated_on", models.DateField(default=django.utils.timezone.localdate)),
                ("depends_on", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dependent_tasks", to="workspace.task")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pixelvault_tasks", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tasks", to="workspace.project")),
            ],
            options={"ordering": ["status", "scheduled_date", "start_time", "-pinned", "title"]},
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.CharField(default=workspace.models.skill_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="General", max_length=100)),
                ("version", models.CharField(default="1.0.0", max_length=40)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("agents", models.JSONField(blank=True, default=list)),
                ("use_cases", models.JSONField(blank=True, default=list)),
                ("filename", models.CharField(default="skill.md", max_length=255)),
                ("content", models.TextField(blank=True)),
                ("attached_file", models.FileField(blank=True, upload_to="skills/%Y/%m/")),
                ("pinned", models.BooleanField(default=False)),
                ("created_on", models.DateField(default=django.utils.timezone.localdate)),
                ("updated_on", models.DateField(default=django.utils.timezone.localdate)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pixelvault_skills", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-pinned", "category", "name"]},
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                ("id", models.CharField(default=workspace.models.annotation_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ("page_key", models.CharField(max_length=40)),
                ("selected_text", models.TextField()),
                ("prefix", models.TextField(blank=True)),
                ("suffix", models.TextField(blank=True)),
                ("color", models.CharField(choices=[("yellow", "Yellow"), ("pink", "Pink"), ("cyan", "Cyan"), ("lime", "Lime")], default="yellow", max_length=16)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pixelvault_annotations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("verb", models.CharField(max_length=80)),
                ("entity_type", models.CharField(blank=True, max_length=40)),
                ("entity_id", models.CharField(blank=True, max_length=64)),
                ("label", models.CharField(blank=True, max_length=250)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pixelvault_activity", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
